ALTER TABLE DEPARTMENT ADD (
  CONSTRAINT FK_DEPT_LOC FOREIGN KEY (LOC_ID) 
    REFERENCES LOC (LOC_ID));
	
ALTER TABLE EMPLOYEE ADD (
  CONSTRAINT FK_EMP_DEPARTMENT FOREIGN KEY (DEPARTMENT_ID) 
    REFERENCES DEPARTMENT (DEPARTMENT_ID));

ALTER TABLE EMPLOYEE ADD (
  CONSTRAINT FK_EMP_JOB FOREIGN KEY (JOB_ID) 
    REFERENCES JOB (JOB_ID));

ALTER TABLE EMPLOYEE ADD (
  CONSTRAINT FK_EMP_MANAGER FOREIGN KEY (MANAGER_ID) 
    REFERENCES EMPLOYEE (EMPLOYEE_ID));
	
	