CONNECT SYSTEM/MANAGER
GRANT CONNECT, RESOURCE TO master IDENTIFIED BY master;
GRANT CONNECT, RESOURCE TO bob IDENTIFIED BY bob;
GRANT CONNECT, RESOURCE TO bill IDENTIFIED BY bill;
SET ECHO OFF FEEDBACK OFF
ALTER USER master DEFAULT TABLESPACE users TEMPORARY TABLESPACE temp;
ALTER USER bob DEFAULT TABLESPACE users TEMPORARY TABLESPACE temp;
ALTER USER bill DEFAULT TABLESPACE users TEMPORARY TABLESPACE temp;
DROP TABLE bob.accounts;
DROP TABLE bill.accounts;
DROP TABLE master.accounts;
DROP SYNONYM bob.accounts;
DROP SYNONYM bill.accounts;
SET ECHO ON FEEDBACK ON
