CREATE OR REPLACE PACKAGE employees_onerow
/*
| Generated by or retrieved from Qnxo - DO NOT MODIFY!
| Qnxo - "Get it right, do it fast" - www.qnxo.com
| Qnxo Universal ID: {1AA62BC9-CA69-4405-9A6D-A74FB4D1A7CE}
| Created On: May 7, 2006 12:30:28
| Created By: HR
*/
IS
   -- Return a cursor variable for one row of data for a primary key.
   FUNCTION onerow_cv ( employee_id_in IN employees_tp.employee_id_t )
      RETURN employees_tp.employees_rc;

   -- Return a record for one row of data for a primary key
   FUNCTION onerow ( employee_id_in IN employees_tp.employee_id_t )
      RETURN employees_tp.employees_rt;

   -- Return TRUE if a row exists for this primary key
   FUNCTION row_exists ( employee_id_in IN employees_tp.employee_id_t )
      RETURN BOOLEAN;

   -- Return a cursor variable for one row by EMP_EMAIL_UK value
   FUNCTION or_emp_email_uk_cv ( email_in IN employees_tp.email_t )
      RETURN employees_tp.employees_rc;

   -- Return a record for one row by EMP_EMAIL_UK value
   FUNCTION or_emp_email_uk ( email_in IN employees_tp.email_t )
      RETURN employees_tp.employees_rt;

   -- Return the primary key value for this unique index value
   FUNCTION pky_emp_email_uk ( email_in IN employees_tp.email_t )
      RETURN employees_tp.employee_id_t;

   -- Number of rows for this EMP_EMAIL_UK value
   FUNCTION num_emp_email_uk ( email_in IN employees_tp.email_t )
      RETURN PLS_INTEGER;

   -- Returns TRUE if at least one row exists for this EMP_EMAIL_UK value
   FUNCTION ex_emp_email_uk ( email_in IN employees_tp.email_t )
      RETURN BOOLEAN;

   -- Return a cursor variable for one row by EMP_NAME value
   FUNCTION or_emp_name_cv (
      first_name_in   IN   employees_tp.first_name_t
    , last_name_in    IN   employees_tp.last_name_t
   )
      RETURN employees_tp.employees_rc;

   -- Return a record for one row by EMP_NAME value
   FUNCTION or_emp_name (
      first_name_in   IN   employees_tp.first_name_t
    , last_name_in    IN   employees_tp.last_name_t
   )
      RETURN employees_tp.employees_rt;

   -- Return the primary key value for this unique index value
   FUNCTION pky_emp_name (
      first_name_in   IN   employees_tp.first_name_t
    , last_name_in    IN   employees_tp.last_name_t
   )
      RETURN employees_tp.employee_id_t;

   -- Returns TRUE if at least one row exists for this EMP_NAME value
   FUNCTION ex_emp_name (
      first_name_in   IN   employees_tp.first_name_t
    , last_name_in    IN   employees_tp.last_name_t
   )
      RETURN BOOLEAN;
END employees_onerow;
/
