set serveroutput on size = 8000;
begin
     DBMS_OUTPUT.enable;
     Main1( 'u1.emp' );
     Main1( 'u1.dept' );
     Main1( 'u1.pk_dept' );
     Main1( 'u1.pk_emp' );
     Main1( 'u1.fk_deptno' );
     Main1( 'u1.vemp' );
     Main1( 'u1.pack1' ); 
     Main1( 'u1.FSum' );
     Main1( 'u1.PSum' );
     Main1( 'u1.Rect' );
     Main1( 'u1.ls_emp' );
     Main1( 'u1.ls_dept' );
     Main1( 'u1.ls_pack1' );
     Main1( 'u1.ls_PSum' );
     Main1( 'u1.ls_FSum' );
     Main1( 'u1.ls_Rect' );
     Main1( 'gs_emp' );
     Main1( 'gs_dept' );
     Main1( 'gs_pack1' );
     Main1( 'gs_PSum' );
     Main1( 'gs_FSum' );
     Main1( 'gs_Rect' );
     Main1( 'u1.ls_emp_ls_emp' );
     Main1( 'u1.ls_dept_ls_dept' );
     Main1( 'u1.ls_pack1_ls_pack1' );
     Main1( 'u1.ls_PSum_ls_PSum' );
     Main1( 'u1.ls_FSum_ls_FSum' );
     Main1( 'u1.ls_Rect_ls_Rect' );
     Main1( 'gs_gs_emp' );
     Main1( 'gs_gs_dept' );
     Main1( 'gs_gs_pack1' );
     Main1( 'gs_gs_PSum' );
     Main1( 'gs_gs_FSum' );
     Main1( 'gs_gs_Rect' );
     Main1( 'u1.ls_emp_gs_emp' );
     Main1( 'u1.ls_dept_gs_dept' );
     Main1( 'u1.ls_pack1_gs_pack1' );
     Main1( 'u1.ls_PSum_gs_PSum' );
     Main1( 'u1.ls_FSum_gs_FSum' );
     Main1( 'u1.ls_Rect_gs_Rect' );
     Main1( 'gs_emp_u1_ls_emp' );
     Main1( 'gs_dept_u1_ls_dept' );
     Main1( 'gs_pack1_u1_ls_pack1' );
     Main1( 'gs_PSum_u1_ls_PSum' );
     Main1( 'gs_FSum_u1_ls_FSum' );
     Main1( 'gs_Rect_u1_ls_Rect' );
end;
/