INSERT INTO UT_GRID ( PACKAGE, PROGNAME, OVERLOAD, TCNAME, MESSAGE, ARGLIST, RETURN_VALUE,
ASSERTION_TYPE, OWNER ) VALUES ( 
'BETWNSTR', 'BETWNSTR', NULL, 'start1', 'Start with 1', 'abcdef;1;3;true', 'abc', 'EQ'
, NULL); 
INSERT INTO UT_GRID ( PACKAGE, PROGNAME, OVERLOAD, TCNAME, MESSAGE, ARGLIST, RETURN_VALUE,
ASSERTION_TYPE, OWNER ) VALUES ( 
'BETWNSTR', 'BETWNSTR', NULL, 'start0', 'Start with 0', 'abcdef;0;2;true', 'ab', 'EQ'
, NULL); 
INSERT INTO UT_GRID ( PACKAGE, PROGNAME, OVERLOAD, TCNAME, MESSAGE, ARGLIST, RETURN_VALUE,
ASSERTION_TYPE, OWNER ) VALUES ( 
'BETWNSTR', 'BETWNSTR', NULL, 'startnull', 'Start with NULL', 'abcdef;!NULL;2;false'
, '!NULL', 'ISNULL', NULL); 
INSERT INTO UT_GRID ( PACKAGE, PROGNAME, OVERLOAD, TCNAME, MESSAGE, ARGLIST, RETURN_VALUE,
ASSERTION_TYPE, OWNER ) VALUES ( 
'BETWNSTR', 'BETWNSTR', NULL, 'endnull', 'End with NULL', 'abcdef;1;!NULL;false', '!NULL'
, 'ISNULL', NULL); 
INSERT INTO UT_GRID ( PACKAGE, PROGNAME, OVERLOAD, TCNAME, MESSAGE, ARGLIST, RETURN_VALUE,
ASSERTION_TYPE, OWNER ) VALUES ( 
'BETWNSTR', 'BETWNSTR', NULL, 'endtoobig', 'End too large', 'abcdef;1;55;true', 'abcdef'
, 'EQ', NULL); 
INSERT INTO UT_GRID ( PACKAGE, PROGNAME, OVERLOAD, TCNAME, MESSAGE, ARGLIST, RETURN_VALUE,
ASSERTION_TYPE, OWNER ) VALUES ( 
'BETWNSTR', 'BETWNSTR', NULL, 'NSPE', 'negative start, positive end', 'abcdef;-1;55;true'
, '!NULL', 'ISNULL', NULL); 
INSERT INTO UT_GRID ( PACKAGE, PROGNAME, OVERLOAD, TCNAME, MESSAGE, ARGLIST, RETURN_VALUE,
ASSERTION_TYPE, OWNER ) VALUES ( 
'BETWNSTR', 'BETWNSTR', NULL, 'NSNE', 'negative start, negative end', 'abcdef;-1;-4;true'
, 'cdef', 'EQ', NULL); 
INSERT INTO UT_GRID ( PACKAGE, PROGNAME, OVERLOAD, TCNAME, MESSAGE, ARGLIST, RETURN_VALUE,
ASSERTION_TYPE, OWNER ) VALUES ( 
'BETWNSTR', 'BETWNSTR', NULL, 'Nullstring', 'Null starting string', '!NULL;1;3;true'
, '!NULL', 'ISNULL', NULL); 
commit;
 
